#!/bin/bash
echo "Local variables:"; (set -o posix; set) | grep -v '^\(_=\|BASH_\|EUID\|GROUPS\|HOME\|HOSTNAME\|HOSTTYPE\|IFS\|LANG\|LOGNAME\|MACHTYPE\|OLDPWD\|OPTIND\|OSTYPE\|PATH\|PIPESTATUS\|POSIXLY_CORRECT\|PPID\|PS1\|PS2\|PS4\|PWD\|SHELL\|SHELLOPTS\|SHLVL\|TERM\|UID\|USER\|_\)=' | sort
echo -e "\nFunctions:"; declare -F | sort
